# https://travis-ci.org/
language: node_js
node_js:
  - '0.10'
  - '0.12'
  - 'iojs-3'
  - '4'
script: 'npm run verify:ci'
install:
  - 'travis_retry npm install'
addons:
  firefox: 'latest'
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_script: "node_modules/.bin/testem launchers"
